apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end

    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels: # labels on the pods
      type: front-end # label on pod above and any pod with this label

# kubectl create -f deployment-definition.yml
# kubectl get deployments

# Deployments will create the replicaset so can check
# kubectl get replicaset
# kubectl get pods