apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort #ClusterIP (Default) or LoadBalancer
  ports:
    - targetPort: 80 #if dont provide, it will assume same as port
      port: 80 #only required port
      nodePort: 30008 #will default in range if not provided
  selector: # matches labels for pod definiton. Links service to pod.
    app: myapp
    type: front-end

# kubectl create -f service-definition.yml
# kubectl get services

# curl http://192.168.1.2:30008